name = "market-intel-api"
main = "index.js"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding        = "DB"
database_name  = "market-intel"
database_id    = "101dd684-e2df-4edf-97ea-f92be920d1e1"
migrations_dir = "migrations"

[triggers]
crons = ["0 */12 * * *"]

[[send_email]]
binding = "EMAIL"

# wrangler secret put WORKER_SECRET
